//! glia-author — AI self-authoring of skill markdown (T13: `glia_save_skill`, V11).
//!
//! Takes a natural-language description and produces a skill markdown file:
//!
//! ```markdown
//! ---
//! name: use-zustand
//! description: When working with React state...
//! stacks: [nextjs, react]
//! ---
//!
//! # Use zustand
//!
//! ...body text...
//! ```
//!
//! The body is generated by an `Author` backend. For tests/dev we ship
//! `TemplateAuthor` which produces a minimal body from the description.
//! For production, `HttpAuthor` calls an OpenAI-compatible endpoint.
//!
//! After authoring, `register` embeds the body, upserts the skill in
//! the DB under the `local::<slug>` namespace (V16), and creates
//! `applies_to_stack` edges for the frontmatter's `stacks` list.

use std::sync::Arc;

use async_trait::async_trait;
use glia_db::{GliaDb, Skill, Stack};
use serde::{Deserialize, Serialize};

/// Frontmatter (YAML at the top of a skill markdown file).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SkillFrontmatter {
    /// Skill slug (kebab-case). Used for `local::<slug>` id (V16).
    pub name: String,
    /// Short human description; used in citations.
    pub description: String,
    /// Stack ids this skill applies to. Drives `applies_to_stack` edges.
    #[serde(default)]
    pub stacks: Vec<String>,
}

impl SkillFrontmatter {
    /// Build a frontmatter with a name + description.
    pub fn new(name: impl Into<String>, description: impl Into<String>) -> Self {
        Self { name: name.into(), description: description.into(), stacks: Vec::new() }
    }

    /// Add a stack. Builder-style.
    pub fn with_stack(mut self, stack: impl Into<String>) -> Self {
        self.stacks.push(stack.into());
        self
    }
}

/// A complete skill markdown document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkillDoc {
    /// Frontmatter.
    pub frontmatter: SkillFrontmatter,
    /// Markdown body (everything after the `---`).
    pub body: String,
}

impl SkillDoc {
    /// Render to a markdown string with `---` frontmatter.
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("---\n");
        out.push_str(&serde_yaml::to_string(&self.frontmatter).expect("frontmatter serializes"));
        out.push_str("---\n\n");
        out.push_str(&self.body);
        if !self.body.ends_with('\n') {
            out.push('\n');
        }
        out
    }
}

/// Errors from authoring / registration.
#[derive(Debug, thiserror::Error)]
pub enum AuthorError {
    /// HTTP / LLM endpoint failed.
    #[error("http: {0}")]
    Http(String),
    /// LLM returned a response we couldn't parse.
    #[error("parse: {0}")]
    Parse(String),
    /// Slug collision (skill already exists in `local::`).
    #[error("skill {0} already exists")]
    AlreadyExists(String),
    /// DB operation failed.
    #[error("db: {0}")]
    Db(#[from] Box<glia_db::DbError>),
    /// Embedder failed.
    #[error("embed: {0}")]
    Embed(#[from] glia_embed::EmbedError),
    /// I/O failed.
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

impl From<glia_db::DbError> for AuthorError {
    fn from(e: glia_db::DbError) -> Self {
        AuthorError::Db(Box::new(e))
    }
}

/// Pluggable authoring backend.
#[async_trait]
pub trait Author: Send + Sync {
    /// Generate a skill doc from a description.
    /// `hint_name` and `hint_stacks` are optional user-supplied hints.
    async fn author(
        &self,
        description: &str,
        hint_name: Option<&str>,
        hint_stacks: &[String],
    ) -> Result<SkillDoc, AuthorError>;

    /// Name of the model/backend (for diagnostics).
    fn backend_name(&self) -> &str;
}

/// Slugify a string into kebab-case ASCII.
///
/// - Lowercases.
/// - Replaces any non-`[a-z0-9-]` sequence with `-`.
/// - Collapses multiple `-` and trims leading/trailing `-`.
/// - Falls back to `"untitled"` if the result is empty.
pub fn slugify(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    let mut last_dash = true;
    for c in name.chars() {
        let lc = c.to_ascii_lowercase();
        if lc.is_ascii_alphanumeric() {
            s.push(lc);
            last_dash = false;
        } else if !last_dash {
            s.push('-');
            last_dash = true;
        }
    }
    let trimmed = s.trim_matches('-').to_string();
    if trimmed.is_empty() {
        "untitled".to_string()
    } else {
        trimmed
    }
}

/// Template author: produces a minimal body from the description.
/// Used in tests and as an offline fallback.
pub struct TemplateAuthor;

#[async_trait]
impl Author for TemplateAuthor {
    async fn author(
        &self,
        description: &str,
        hint_name: Option<&str>,
        hint_stacks: &[String],
    ) -> Result<SkillDoc, AuthorError> {
        let name = hint_name.map(slugify).unwrap_or_else(|| slugify(description));
        let body = format!("# {}\n\n{}\n", titlecase(&name.replace('-', " ")), description.trim());
        let mut fm = SkillFrontmatter::new(&name, description.trim());
        fm.stacks = hint_stacks.to_vec();
        Ok(SkillDoc { frontmatter: fm, body })
    }

    fn backend_name(&self) -> &str {
        "template"
    }
}

/// HTTP author: calls an OpenAI-compatible endpoint to generate the body.
pub struct HttpAuthor {
    /// Base URL (e.g., `https://api.openai.com/v1`).
    pub base_url: String,
    /// Bearer token.
    pub api_key: String,
    /// Model name (e.g., `gpt-4o-mini`).
    pub model: String,
    client: reqwest::Client,
}

impl HttpAuthor {
    /// Build a new HTTP author.
    pub fn new(base_url: impl Into<String>, api_key: impl Into<String>, model: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into(),
            api_key: api_key.into(),
            model: model.into(),
            client: reqwest::Client::builder()
                .timeout(std::time::Duration::from_secs(60))
                .build()
                .expect("reqwest client"),
        }
    }
}

#[async_trait]
impl Author for HttpAuthor {
    async fn author(
        &self,
        description: &str,
        hint_name: Option<&str>,
        hint_stacks: &[String],
    ) -> Result<SkillDoc, AuthorError> {
        let mut hint = String::new();
        if let Some(n) = hint_name {
            hint.push_str(&format!("\nSkill name hint: {}\n", n));
        }
        if !hint_stacks.is_empty() {
            hint.push_str(&format!("\nStacks: {}\n", hint_stacks.join(", ")));
        }
        let system = "You are a Glia skill author. Produce a concise markdown skill body (max 300 words) that captures rules, do/don'ts, and concrete examples. Start with a # heading matching the skill name. No preamble.";
        let user = format!("Description: {}\n{}", description, hint);

        let body = serde_json::json!({
            "model": self.model,
            "max_tokens": 600,
            "temperature": 0.2,
            "messages": [
                { "role": "system", "content": system },
                { "role": "user", "content": user },
            ],
        });

        let url = format!("{}/chat/completions", self.base_url.trim_end_matches('/'));
        let resp = self
            .client
            .post(&url)
            .bearer_auth(&self.api_key)
            .json(&body)
            .send()
            .await
            .map_err(|e| AuthorError::Http(e.to_string()))?;
        let status = resp.status();
        let text = resp.text().await.map_err(|e| AuthorError::Http(e.to_string()))?;
        if !status.is_success() {
            return Err(AuthorError::Http(format!("{}: {}", status, text)));
        }
        let parsed: ChatResponse = serde_json::from_str(&text)
            .map_err(|e| AuthorError::Parse(e.to_string()))?;
        let generated = parsed
            .choices
            .into_iter()
            .next()
            .map(|c| c.message.content)
            .ok_or_else(|| AuthorError::Parse("no choices in response".into()))?;

        // Extract first line as title; if missing, fall back to slug.
        let title = generated
            .lines()
            .find_map(|l| l.strip_prefix("# ").map(|s| s.trim().to_string()))
            .unwrap_or_else(|| slugify(description));
        let name = hint_name.map(slugify).unwrap_or_else(|| slugify(&title));
        let mut fm = SkillFrontmatter::new(&name, description.trim());
        fm.stacks = hint_stacks.to_vec();
        Ok(SkillDoc { frontmatter: fm, body: generated })
    }

    fn backend_name(&self) -> &str {
        &self.model
    }
}

#[derive(Debug, Deserialize)]
struct ChatResponse {
    choices: Vec<ChatChoice>,
}

#[derive(Debug, Deserialize)]
struct ChatChoice {
    message: ChatMessage,
}

#[derive(Debug, Deserialize)]
struct ChatMessage {
    content: String,
}

/// Title-case a string (first char of each word uppercased).
fn titlecase(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut capitalize_next = true;
    for c in s.chars() {
        if c.is_whitespace() {
            out.push(c);
            capitalize_next = true;
        } else if capitalize_next {
            for u in c.to_uppercase() {
                out.push(u);
            }
            capitalize_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Register a skill doc into the DB.
///
/// 1. Slug → id `local::<slug>` (V16).
/// 2. Upsert as a `skill` record with the body content.
/// 3. Embed the body, store vector on the record.
/// 4. For each stack in the frontmatter, upsert the stack + create
///    an `applies_to_stack` edge.
pub async fn register(
    doc: &SkillDoc,
    db: &GliaDb,
    embedder: &glia_embed::Embedder,
) -> Result<String, AuthorError> {
    let id = format!("local::{}", doc.frontmatter.name);
    if db.get_skill(&id).await?.is_some() {
        return Err(AuthorError::AlreadyExists(id));
    }
    let vector = embedder.embed(&doc.body)?;
    let now = chrono::Utc::now().to_rfc3339();
    let record = Skill {
        content: doc.body.clone(),
        source: format!("local::{}.md", doc.frontmatter.name),
        embedding: vector,
        updated_at: now,
    };
    db.upsert_skill(&id, record).await?;
    for stack in &doc.frontmatter.stacks {
        db.upsert_stack(stack, Stack { name: stack.clone() }).await?;
        db.relate_skill_applies_to_stack(&id, stack).await?;
    }
    Ok(id)
}

/// High-level entrypoint: author + register in one call.
pub struct SkillAuthor {
    backend: Arc<dyn Author>,
}

impl SkillAuthor {
    /// Build a new `SkillAuthor` with the given backend.
    pub fn new(backend: Arc<dyn Author>) -> Self {
        Self { backend }
    }

    /// Author a skill from a description and register it.
    /// Returns the new skill id (`local::<slug>`).
    pub async fn save(
        &self,
        description: &str,
        hint_name: Option<&str>,
        hint_stacks: &[String],
        db: &GliaDb,
        embedder: &glia_embed::Embedder,
    ) -> Result<String, AuthorError> {
        let doc = self.backend.author(description, hint_name, hint_stacks).await?;
        register(&doc, db, embedder).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use glia_db::Connection;

    async fn empty_db() -> Arc<GliaDb> {
        let db = Arc::new(GliaDb::connect(Connection::Memory).await.unwrap());
        db.init_schema().await.unwrap();
        db
    }

    fn emb() -> glia_embed::Embedder {
        glia_embed::Embedder::new().expect("embedder")
    }

    #[tokio::test]
    async fn slugify_basic() {
        assert_eq!(slugify("Use Zustand"), "use-zustand");
        assert_eq!(slugify("  hello   world  "), "hello-world");
        assert_eq!(slugify("foo_bar baz"), "foo-bar-baz");
        assert_eq!(slugify("---"), "untitled");
        assert_eq!(slugify(""), "untitled");
    }

    #[tokio::test]
    async fn template_author_produces_doc() {
        let a = TemplateAuthor;
        let doc = a
            .author("Use zustand for React state in Next.js", Some("use-zustand"), &["nextjs".into()])
            .await
            .unwrap();
        assert_eq!(doc.frontmatter.name, "use-zustand");
        assert_eq!(doc.frontmatter.stacks, vec!["nextjs"]);
        assert!(doc.body.contains("Use zustand"));
    }

    #[tokio::test]
    async fn template_author_slug_from_description() {
        let a = TemplateAuthor;
        let doc = a.author("Set up Supabase auth", None, &[]).await.unwrap();
        assert_eq!(doc.frontmatter.name, "set-up-supabase-auth");
    }

    #[test]
    fn doc_render_includes_frontmatter() {
        let doc = SkillDoc {
            frontmatter: SkillFrontmatter::new("foo", "bar").with_stack("nextjs"),
            body: "# Foo\n\nbody text".into(),
        };
        let md = doc.render();
        assert!(md.starts_with("---\n"));
        assert!(md.contains("name: foo"));
        assert!(md.contains("stacks:"));
        assert!(md.contains("body text"));
    }

    #[test]
    fn frontmatter_round_trip() {
        let fm = SkillFrontmatter::new("foo", "bar").with_stack("s1");
        let y = serde_yaml::to_string(&fm).unwrap();
        let back: SkillFrontmatter = serde_yaml::from_str(&y).unwrap();
        assert_eq!(back, fm);
    }

    #[test]
    fn titlecase_capitalizes_words() {
        assert_eq!(titlecase("hello world"), "Hello World");
        assert_eq!(titlecase(""), "");
    }

    #[tokio::test]
    async fn register_inserts_skill_with_embedding() {
        let db = empty_db().await;
        let doc = SkillDoc {
            frontmatter: SkillFrontmatter::new("use-zustand", "Use zustand").with_stack("nextjs"),
            body: "Use zustand for React state.".into(),
        };
        let id = register(&doc, &db, &emb()).await.unwrap();
        assert_eq!(id, "local::use-zustand");
        let skill = db.get_skill(&id).await.unwrap().unwrap();
        assert_eq!(skill.content, "Use zustand for React state.");
        assert_eq!(skill.embedding.len(), 384);
        let stacks = db.skills_for_stack("nextjs").await.unwrap();
        assert!(stacks.iter().any(|s| s.source.contains("use-zustand")));
    }

    #[tokio::test]
    async fn register_rejects_duplicate() {
        let db = empty_db().await;
        let doc = SkillDoc {
            frontmatter: SkillFrontmatter::new("dup", "x"),
            body: "x".into(),
        };
        register(&doc, &db, &emb()).await.unwrap();
        let err = register(&doc, &db, &emb()).await.unwrap_err();
        assert!(matches!(err, AuthorError::AlreadyExists(_)));
    }

    #[tokio::test]
    async fn skill_author_save_end_to_end() {
        let db = empty_db().await;
        let sa = SkillAuthor::new(Arc::new(TemplateAuthor));
        let id = sa
            .save(
                "Use zustand for React state",
                Some("use-zustand"),
                &["nextjs".into(), "react".into()],
                &db,
                &emb(),
            )
            .await
            .unwrap();
        assert_eq!(id, "local::use-zustand");
        let skill = db.get_skill(&id).await.unwrap().unwrap();
        assert!(skill.content.contains("zustand"));
    }
}
